inherit_from:
  - .rubocop_todo.yml
  - .rubocop_strict.yml
  - .rubocop_style.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - '**/bin/**/*'
    - '**/config/environments/**/*'
    - '**/config/application.rb'
    - '**/config/environment.rb'
    - '**/config/puma.rb'
    - '**/config/boot.rb'
    - '**/spec/dummy/**/*'
    - '**/spec/*_helper.rb'
    - '**/spec/**/support/**/*'
    - 'lib/generators/**/*'