inherit_gem:
  boost-styles:
    - rubocop_default.yml

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'spec/dummy/**/*'