language: ruby
rvm:
  - 2.6.5
cache: bundler
bundler_args: --without production
sudo: false
script:
  - grep -rl "ActiveRecord::Migration$" db | xargs sed -i 's/ActiveRecord::Migration/ActiveRecord::Migration[4.2]/g'
  - RAILS_ENV=test bin/rails db:migrate
  - bundle exec rspec
  - bundle exec rubocop

addons:
  code_climate:
    repo_token:
      secure: CODE_CLIMATE_API_KEY
